# Import Lib

In [1]:
import pandas as pd
import numpy as np
import nltk
import string
import re

In [18]:
df = pd.read_csv('HasilScraping.csv')
df.drop(columns=df.columns[0], axis=1, inplace=True)
df

,id,date,username,tweet,latitude,longitude
0,1387917769501515778,2021-04-29 23:52:37+00:00,MaseebAkhter,3RD JUMMA MUBARAK\nðŸ’– ðŸ’– ðŸ’– ðŸ’– ðŸ’– \n#Ramadan2021 #w...,24.972077,67.064381
1,1387915894769160192,2021-04-29 23:45:10+00:00,TANTRAYSAQLAIN1,@bollywood_life Lanat hai bollywood par jis na...,33.524595,74.119746
2,1387914934533513220,2021-04-29 23:41:21+00:00,PolsekPlaju3,Bersama Kita Lawan Covid-19\n\nSinergitas TNI-...,-3.190822,104.794609
3,1387913431865610244,2021-04-29 23:35:22+00:00,irfania_real,Jummah Mubarak \n#irfaniarealestate #jummahmub...,31.315389,74.222395
4,1387911958393987075,2021-04-29 23:29:31+00:00,kenny_thok,Semangat ya neng!!!!\nIsolasi pake 3M sek....\...,-2.455096,111.930698
...,...,...,...,...,...,...
9333,1536525461077262336,2022-06-14 01:46:31+00:00,natasya_puspa4,Pak Jokowi minta para menterinya mewaspadai da...,-6.364100,106.799599
9334,1536525113289752576,2022-06-14 01:45:08+00:00,Irwijaya_q,Pak Jokowi minta para menterinya mewaspadai da...,-6.364100,106.799599
9335,1536515216665899013,2022-06-14 01:05:49+00:00,Agistasyahka,Penyebaran virus Omicron BA.4 dan BA.5 ini leb...,-6.301652,106.974561
9336,1536358141377384448,2022-06-13 14:41:39+00:00,Ardi_Wdyto,Varian baru omicron lagi :),-7.776581,113.198255
9337,1536251604772745216,2022-06-13 07:38:19+00:00,gemaposID,BREAKING NEWS!!\nOmicron BA.4 dan BA.5 resmi t...,-6.218042,106.857762

# Cleaning Data

In [21]:
#Pembersihan Data (Tahap 1)

#remove mention
def remove_pattern(tweet,pattern):
    r = re.findall(pattern,tweet)
    for i in r:
        tweet = re.sub(i, '',tweet)
    return tweet

df['tweet_clean'] = np.vectorize(remove_pattern)(df['tweet'], "@[\w]*")

def clean_data(tweet):    
    #remove hastag, link dan tandabaca ^dan kata yg menyertainya 
    tweet = ' '.join(re.sub('([#^][A-Za-z0-9]+)|(\w+:\/\/\S+)',' ',tweet).split())
    
    #remove non ASCII (ex:emoticon)
    tweet = tweet.encode('ascii','replace').decode('ascii') 
        
    #remove number 
    tweet = re.sub(r'\d+','', tweet)
        
    #remove multiple whitespace into single whitespace
    tweet = re.sub('\s+',' ',tweet)
    
    #remove whitespace leading & trailing
    tweet = tweet.strip()
    
    #replace word repetition ('memuaskannnn' menjadi 'memuaskann')
    tweet = re.sub(r'(.)\1+', r'\1\1',tweet)
    
    #remove single character
    tweet = re.sub(r"\b[a-zA-Z]\b","",tweet)
    
    #remove punctuation (tanda baca)
    remove = string.punctuation
    translator = str.maketrans(remove, ' '*len(remove))
    tweet = tweet.translate(translator)
    
    return tweet.replace('http://',' ').replace('https://',' ')

df['tweet_clean'] = df['tweet_clean'].apply(clean_data)

df.tail(5)

,id,date,username,tweet,latitude,longitude,tweet_clean
9333,1536525461077262336,2022-06-14 01:46:31+00:00,natasya_puspa4,Pak Jokowi minta para menterinya mewaspadai da...,-6.364100,106.799599,Pak Jokowi minta para menterinya mewaspadai da...
9334,1536525113289752576,2022-06-14 01:45:08+00:00,Irwijaya_q,Pak Jokowi minta para menterinya mewaspadai da...,-6.364100,106.799599,Pak Jokowi minta para menterinya mewaspadai da...
9335,1536515216665899013,2022-06-14 01:05:49+00:00,Agistasyahka,Penyebaran virus Omicron BA.4 dan BA.5 ini leb...,-6.301652,106.974561,Penyebaran virus Omicron BA dan BA ini lebih...
9336,1536358141377384448,2022-06-13 14:41:39+00:00,Ardi_Wdyto,Varian baru omicron lagi :),-7.776581,113.198255,Varian baru omicron lagi
9337,1536251604772745216,2022-06-13 07:38:19+00:00,gemaposID,BREAKING NEWS!!\nOmicron BA.4 dan BA.5 resmi t...,-6.218042,106.857762,BREAKING NEWS Omicron BA dan BA resmi terd...

In [23]:
df.shape

(9338, 7)

In [24]:
# Cleaning Data (2)

def clean_data1(tweet):               
    #remove multiple whitespace into single whitespace
    tweet = re.sub('\s+',' ',tweet)
    
    #remove whitespace leading & trailing
    tweet = tweet.strip()
    
    return tweet

df['tweet_clean'] = df['tweet_clean'].apply(clean_data1)

df.tail(5)

,id,date,username,tweet,latitude,longitude,tweet_clean
9333,1536525461077262336,2022-06-14 01:46:31+00:00,natasya_puspa4,Pak Jokowi minta para menterinya mewaspadai da...,-6.364100,106.799599,Pak Jokowi minta para menterinya mewaspadai da...
9334,1536525113289752576,2022-06-14 01:45:08+00:00,Irwijaya_q,Pak Jokowi minta para menterinya mewaspadai da...,-6.364100,106.799599,Pak Jokowi minta para menterinya mewaspadai da...
9335,1536515216665899013,2022-06-14 01:05:49+00:00,Agistasyahka,Penyebaran virus Omicron BA.4 dan BA.5 ini leb...,-6.301652,106.974561,Penyebaran virus Omicron BA dan BA ini lebih c...
9336,1536358141377384448,2022-06-13 14:41:39+00:00,Ardi_Wdyto,Varian baru omicron lagi :),-7.776581,113.198255,Varian baru omicron lagi
9337,1536251604772745216,2022-06-13 07:38:19+00:00,gemaposID,BREAKING NEWS!!\nOmicron BA.4 dan BA.5 resmi t...,-6.218042,106.857762,BREAKING NEWS Omicron BA dan BA resmi terdetek...

# Case Folding

In [25]:
def casefold_data(tweet):
    tweet=tweet.lower()
    return tweet
    
df['tweet_clean'] = df['tweet_clean'].apply(casefold_data)

df

,id,date,username,tweet,latitude,longitude,tweet_clean
0,1387917769501515778,2021-04-29 23:52:37+00:00,MaseebAkhter,3RD JUMMA MUBARAK\nðŸ’– ðŸ’– ðŸ’– ðŸ’– ðŸ’– \n#Ramadan2021 #w...,24.972077,67.064381,rd jumma mubarak
1,1387915894769160192,2021-04-29 23:45:10+00:00,TANTRAYSAQLAIN1,@bollywood_life Lanat hai bollywood par jis na...,33.524595,74.119746,lanat hai bollywood par jis na india leya dona...
2,1387914934533513220,2021-04-29 23:41:21+00:00,PolsekPlaju3,Bersama Kita Lawan Covid-19\n\nSinergitas TNI-...,-3.190822,104.794609,bersama kita lawan covid sinergitas tni polri ...
3,1387913431865610244,2021-04-29 23:35:22+00:00,irfania_real,Jummah Mubarak \n#irfaniarealestate #jummahmub...,31.315389,74.222395,jummah mubarak
4,1387911958393987075,2021-04-29 23:29:31+00:00,kenny_thok,Semangat ya neng!!!!\nIsolasi pake 3M sek....\...,-2.455096,111.930698,semangat ya neng isolasi pake sek pondok derit...
...,...,...,...,...,...,...,...
9333,1536525461077262336,2022-06-14 01:46:31+00:00,natasya_puspa4,Pak Jokowi minta para menterinya mewaspadai da...,-6.364100,106.799599,pak jokowi minta para menterinya mewaspadai da...
9334,1536525113289752576,2022-06-14 01:45:08+00:00,Irwijaya_q,Pak Jokowi minta para menterinya mewaspadai da...,-6.364100,106.799599,pak jokowi minta para menterinya mewaspadai da...
9335,1536515216665899013,2022-06-14 01:05:49+00:00,Agistasyahka,Penyebaran virus Omicron BA.4 dan BA.5 ini leb...,-6.301652,106.974561,penyebaran virus omicron ba dan ba ini lebih c...
9336,1536358141377384448,2022-06-13 14:41:39+00:00,Ardi_Wdyto,Varian baru omicron lagi :),-7.776581,113.198255,varian baru omicron lagi
9337,1536251604772745216,2022-06-13 07:38:19+00:00,gemaposID,BREAKING NEWS!!\nOmicron BA.4 dan BA.5 resmi t...,-6.218042,106.857762,breaking news omicron ba dan ba resmi terdetek...

In [26]:
#drop duplicates
df.drop_duplicates(subset="tweet_clean", keep="first", inplace=True)
df

,id,date,username,tweet,latitude,longitude,tweet_clean
0,1387917769501515778,2021-04-29 23:52:37+00:00,MaseebAkhter,3RD JUMMA MUBARAK\nðŸ’– ðŸ’– ðŸ’– ðŸ’– ðŸ’– \n#Ramadan2021 #w...,24.972077,67.064381,rd jumma mubarak
1,1387915894769160192,2021-04-29 23:45:10+00:00,TANTRAYSAQLAIN1,@bollywood_life Lanat hai bollywood par jis na...,33.524595,74.119746,lanat hai bollywood par jis na india leya dona...
2,1387914934533513220,2021-04-29 23:41:21+00:00,PolsekPlaju3,Bersama Kita Lawan Covid-19\n\nSinergitas TNI-...,-3.190822,104.794609,bersama kita lawan covid sinergitas tni polri ...
3,1387913431865610244,2021-04-29 23:35:22+00:00,irfania_real,Jummah Mubarak \n#irfaniarealestate #jummahmub...,31.315389,74.222395,jummah mubarak
4,1387911958393987075,2021-04-29 23:29:31+00:00,kenny_thok,Semangat ya neng!!!!\nIsolasi pake 3M sek....\...,-2.455096,111.930698,semangat ya neng isolasi pake sek pondok derit...
...,...,...,...,...,...,...,...
9332,1536673294782709760,2022-06-14 11:33:58+00:00,StellaSuwardi,Vaksinasi booster dapat meningkatkan imunitas ...,-6.297602,106.770437,vaksinasi booster dapat meningkatkan imunitas ...
9333,1536525461077262336,2022-06-14 01:46:31+00:00,natasya_puspa4,Pak Jokowi minta para menterinya mewaspadai da...,-6.364100,106.799599,pak jokowi minta para menterinya mewaspadai da...
9335,1536515216665899013,2022-06-14 01:05:49+00:00,Agistasyahka,Penyebaran virus Omicron BA.4 dan BA.5 ini leb...,-6.301652,106.974561,penyebaran virus omicron ba dan ba ini lebih c...
9336,1536358141377384448,2022-06-13 14:41:39+00:00,Ardi_Wdyto,Varian baru omicron lagi :),-7.776581,113.198255,varian baru omicron lagi
9337,1536251604772745216,2022-06-13 07:38:19+00:00,gemaposID,BREAKING NEWS!!\nOmicron BA.4 dan BA.5 resmi t...,-6.218042,106.857762,breaking news omicron ba dan ba resmi terdetek...

# Tokenizing

In [27]:
from nltk.tokenize import word_tokenize

def word_tokenize_wrapper(text):
    return word_tokenize(text)

df['tweet_clean'] = df['tweet_clean'].apply(word_tokenize_wrapper)

df.head(5)

,id,date,username,tweet,latitude,longitude,tweet_clean
0,1387917769501515778,2021-04-29 23:52:37+00:00,MaseebAkhter,3RD JUMMA MUBARAK\nðŸ’– ðŸ’– ðŸ’– ðŸ’– ðŸ’– \n#Ramadan2021 #w...,24.972077,67.064381,"[rd, jumma, mubarak]"
1,1387915894769160192,2021-04-29 23:45:10+00:00,TANTRAYSAQLAIN1,@bollywood_life Lanat hai bollywood par jis na...,33.524595,74.119746,"[lanat, hai, bollywood, par, jis, na, india, l..."
2,1387914934533513220,2021-04-29 23:41:21+00:00,PolsekPlaju3,Bersama Kita Lawan Covid-19\n\nSinergitas TNI-...,-3.190822,104.794609,"[bersama, kita, lawan, covid, sinergitas, tni,..."
3,1387913431865610244,2021-04-29 23:35:22+00:00,irfania_real,Jummah Mubarak \n#irfaniarealestate #jummahmub...,31.315389,74.222395,"[jummah, mubarak]"
4,1387911958393987075,2021-04-29 23:29:31+00:00,kenny_thok,Semangat ya neng!!!!\nIsolasi pake 3M sek....\...,-2.455096,111.930698,"[semangat, ya, neng, isolasi, pake, sek, pondo..."

In [30]:
df.drop(df.index[1], inplace=True)
df

,id,date,username,tweet,latitude,longitude,tweet_clean
0,1387917769501515778,2021-04-29 23:52:37+00:00,MaseebAkhter,3RD JUMMA MUBARAK\nðŸ’– ðŸ’– ðŸ’– ðŸ’– ðŸ’– \n#Ramadan2021 #w...,24.972077,67.064381,"[rd, jumma, mubarak]"
2,1387914934533513220,2021-04-29 23:41:21+00:00,PolsekPlaju3,Bersama Kita Lawan Covid-19\n\nSinergitas TNI-...,-3.190822,104.794609,"[bersama, kita, lawan, covid, sinergitas, tni,..."
3,1387913431865610244,2021-04-29 23:35:22+00:00,irfania_real,Jummah Mubarak \n#irfaniarealestate #jummahmub...,31.315389,74.222395,"[jummah, mubarak]"
4,1387911958393987075,2021-04-29 23:29:31+00:00,kenny_thok,Semangat ya neng!!!!\nIsolasi pake 3M sek....\...,-2.455096,111.930698,"[semangat, ya, neng, isolasi, pake, sek, pondo..."
5,1387907774441566213,2021-04-29 23:12:54+00:00,kejarirohul,"Pada hari Kamis tanggal 29 April 2021, Kepala ...",0.902542,100.308263,"[pada, hari, kamis, tanggal, april, kepala, se..."
...,...,...,...,...,...,...,...
9332,1536673294782709760,2022-06-14 11:33:58+00:00,StellaSuwardi,Vaksinasi booster dapat meningkatkan imunitas ...,-6.297602,106.770437,"[vaksinasi, booster, dapat, meningkatkan, imun..."
9333,1536525461077262336,2022-06-14 01:46:31+00:00,natasya_puspa4,Pak Jokowi minta para menterinya mewaspadai da...,-6.364100,106.799599,"[pak, jokowi, minta, para, menterinya, mewaspa..."
9335,1536515216665899013,2022-06-14 01:05:49+00:00,Agistasyahka,Penyebaran virus Omicron BA.4 dan BA.5 ini leb...,-6.301652,106.974561,"[penyebaran, virus, omicron, ba, dan, ba, ini,..."
9336,1536358141377384448,2022-06-13 14:41:39+00:00,Ardi_Wdyto,Varian baru omicron lagi :),-7.776581,113.198255,"[varian, baru, omicron, lagi]"
9337,1536251604772745216,2022-06-13 07:38:19+00:00,gemaposID,BREAKING NEWS!!\nOmicron BA.4 dan BA.5 resmi t...,-6.218042,106.857762,"[breaking, news, omicron, ba, dan, ba, resmi, ..."

# Normalization Word

In [31]:
normalized_word = pd.read_csv("normalisasi.csv")
normalized_word_dict = {}

for index, row in normalized_word.iterrows():
    if row[0] not in normalized_word_dict:
        normalized_word_dict[row[0]]=row[1]
        
def normalized_term(document):
    return [normalized_word_dict[term] if term in normalized_word_dict else term for term in document]

df['tweet_normalize'] = df['tweet_clean'].apply(normalized_term)

df.head(5)

,id,date,username,tweet,latitude,longitude,tweet_clean,tweet_normalize
0,1387917769501515778,2021-04-29 23:52:37+00:00,MaseebAkhter,3RD JUMMA MUBARAK\nðŸ’– ðŸ’– ðŸ’– ðŸ’– ðŸ’– \n#Ramadan2021 #w...,24.972077,67.064381,"[rd, jumma, mubarak]","[rd, jumma, mubarak]"
2,1387914934533513220,2021-04-29 23:41:21+00:00,PolsekPlaju3,Bersama Kita Lawan Covid-19\n\nSinergitas TNI-...,-3.190822,104.794609,"[bersama, kita, lawan, covid, sinergitas, tni,...","[bersama, kita, lawan, covid, sinergitas, tni,..."
3,1387913431865610244,2021-04-29 23:35:22+00:00,irfania_real,Jummah Mubarak \n#irfaniarealestate #jummahmub...,31.315389,74.222395,"[jummah, mubarak]","[jummah, mubarak]"
4,1387911958393987075,2021-04-29 23:29:31+00:00,kenny_thok,Semangat ya neng!!!!\nIsolasi pake 3M sek....\...,-2.455096,111.930698,"[semangat, ya, neng, isolasi, pake, sek, pondo...","[semangat, ya, neng, isolasi, pakai, sek, pond..."
5,1387907774441566213,2021-04-29 23:12:54+00:00,kejarirohul,"Pada hari Kamis tanggal 29 April 2021, Kepala ...",0.902542,100.308263,"[pada, hari, kamis, tanggal, april, kepala, se...","[pada, hari, kamis, tanggal, april, kepala, se..."

# Filtering (Stopword Removal)

In [33]:
from nltk.corpus import stopwords 
list_stopwords = stopwords.words('indonesian')

#menambah stopword dari file csv
txt_stopword = pd.read_csv('stopword_id.csv', names= ["stopwords"], header = None)

# convert stopword string to list & append additional stopword
list_stopwords.extend(txt_stopword["stopwords"][0].split(' '))

# convert list to dictionary
list_stopwords = set(list_stopwords)

#nenghapus stopwords
def stopword_removal(words):
    return [word for word in words if word not in list_stopwords]

df['tweet_stopword'] = df['tweet_normalize'].apply(stopword_removal)

df.head(10)

,id,date,username,tweet,latitude,longitude,tweet_clean,tweet_normalize,tweet_stopword
0,1387917769501515778,2021-04-29 23:52:37+00:00,MaseebAkhter,3RD JUMMA MUBARAK\nðŸ’– ðŸ’– ðŸ’– ðŸ’– ðŸ’– \n#Ramadan2021 #w...,24.972077,67.064381,"[rd, jumma, mubarak]","[rd, jumma, mubarak]","[rd, jumma, mubarak]"
2,1387914934533513220,2021-04-29 23:41:21+00:00,PolsekPlaju3,Bersama Kita Lawan Covid-19\n\nSinergitas TNI-...,-3.190822,104.794609,"[bersama, kita, lawan, covid, sinergitas, tni,...","[bersama, kita, lawan, covid, sinergitas, tni,...","[lawan, covid, sinergitas, tni, polri, mencega..."
3,1387913431865610244,2021-04-29 23:35:22+00:00,irfania_real,Jummah Mubarak \n#irfaniarealestate #jummahmub...,31.315389,74.222395,"[jummah, mubarak]","[jummah, mubarak]","[jummah, mubarak]"
4,1387911958393987075,2021-04-29 23:29:31+00:00,kenny_thok,Semangat ya neng!!!!\nIsolasi pake 3M sek....\...,-2.455096,111.930698,"[semangat, ya, neng, isolasi, pake, sek, pondo...","[semangat, ya, neng, isolasi, pakai, sek, pond...","[semangat, ya, neng, isolasi, pakai, sek, pond..."
5,1387907774441566213,2021-04-29 23:12:54+00:00,kejarirohul,"Pada hari Kamis tanggal 29 April 2021, Kepala ...",0.902542,100.308263,"[pada, hari, kamis, tanggal, april, kepala, se...","[pada, hari, kamis, tanggal, april, kepala, se...","[kamis, tanggal, april, kepala, seksi, intelij..."
6,1387900087645265921,2021-04-29 22:42:21+00:00,eye_healer,System ko changa si se nanga si karnewalo.. ja...,24.373560,92.419839,"[system, ko, changa, si, se, nanga, si, karnew...","[system, ko, changa, si, se, nanga, si, karnew...","[system, ko, changa, si, nanga, si, karnewalo,..."
7,1387897766102269952,2021-04-29 22:33:07+00:00,sek_batulayar,Jangan Mudik\nBersama Cegah Penyebaran COVID-1...,-8.623126,116.069081,"[jangan, mudik, bersama, cegah, penyebaran, co...","[jangan, mudik, bersama, cegah, penyebaran, co...","[mudik, cegah, penyebaran, covid]"
8,1387886247444549633,2021-04-29 21:47:21+00:00,katapang_polsek,Penerapan protokol kesehatan terhadap pengunju...,-7.031984,107.534391,"[penerapan, protokol, kesehatan, terhadap, pen...","[penerapan, protokol, kesehatan, terhadap, pen...","[penerapan, protokol, kesehatan, pengunjung, t..."
9,1387885703405572098,2021-04-29 21:45:12+00:00,NabialCG,"Semoga, dan tetap disiplin menjalani prokes\nA...",-7.773728,110.304567,"[semoga, dan, tetap, disiplin, menjalani, prok...","[semoga, dan, tetap, disiplin, menjalani, prok...","[semoga, disiplin, menjalani, prokes, aamiin]"
10,1387871604349173765,2021-04-29 20:49:10+00:00,abah_sidik,LPBI NU CIANJUR tergabung bersama TIM ALIF Rel...,-6.739744,107.145685,"[lpbi, nu, cianjur, tergabung, bersama, tim, a...","[lpbi, nu, cianjur, tergabung, bersama, tim, a...","[lpbi, nu, cianjur, tergabung, tim, alif, rela..."

In [34]:
df.to_csv('PreProcessBeforeStemming.csv')
df

,id,date,username,tweet,latitude,longitude,tweet_clean,tweet_normalize,tweet_stopword
0,1387917769501515778,2021-04-29 23:52:37+00:00,MaseebAkhter,3RD JUMMA MUBARAK\nðŸ’– ðŸ’– ðŸ’– ðŸ’– ðŸ’– \n#Ramadan2021 #w...,24.972077,67.064381,"[rd, jumma, mubarak]","[rd, jumma, mubarak]","[rd, jumma, mubarak]"
2,1387914934533513220,2021-04-29 23:41:21+00:00,PolsekPlaju3,Bersama Kita Lawan Covid-19\n\nSinergitas TNI-...,-3.190822,104.794609,"[bersama, kita, lawan, covid, sinergitas, tni,...","[bersama, kita, lawan, covid, sinergitas, tni,...","[lawan, covid, sinergitas, tni, polri, mencega..."
3,1387913431865610244,2021-04-29 23:35:22+00:00,irfania_real,Jummah Mubarak \n#irfaniarealestate #jummahmub...,31.315389,74.222395,"[jummah, mubarak]","[jummah, mubarak]","[jummah, mubarak]"
4,1387911958393987075,2021-04-29 23:29:31+00:00,kenny_thok,Semangat ya neng!!!!\nIsolasi pake 3M sek....\...,-2.455096,111.930698,"[semangat, ya, neng, isolasi, pake, sek, pondo...","[semangat, ya, neng, isolasi, pakai, sek, pond...","[semangat, ya, neng, isolasi, pakai, sek, pond..."
5,1387907774441566213,2021-04-29 23:12:54+00:00,kejarirohul,"Pada hari Kamis tanggal 29 April 2021, Kepala ...",0.902542,100.308263,"[pada, hari, kamis, tanggal, april, kepala, se...","[pada, hari, kamis, tanggal, april, kepala, se...","[kamis, tanggal, april, kepala, seksi, intelij..."
...,...,...,...,...,...,...,...,...,...
9332,1536673294782709760,2022-06-14 11:33:58+00:00,StellaSuwardi,Vaksinasi booster dapat meningkatkan imunitas ...,-6.297602,106.770437,"[vaksinasi, booster, dapat, meningkatkan, imun...","[vaksinasi, booster, dapat, meningkatkan, imun...","[vaksinasi, booster, meningkatkan, imunitas, v..."
9333,1536525461077262336,2022-06-14 01:46:31+00:00,natasya_puspa4,Pak Jokowi minta para menterinya mewaspadai da...,-6.364100,106.799599,"[pak, jokowi, minta, para, menterinya, mewaspa...","[pak, jokowi, minta, para, menterinya, mewaspa...","[jokowi, menterinya, mewaspadai, hati, hati, v..."
9335,1536515216665899013,2022-06-14 01:05:49+00:00,Agistasyahka,Penyebaran virus Omicron BA.4 dan BA.5 ini leb...,-6.301652,106.974561,"[penyebaran, virus, omicron, ba, dan, ba, ini,...","[penyebaran, virus, omicron, ba, dan, ba, ini,...","[penyebaran, virus, omicron, ba, ba, cepat, di..."
9336,1536358141377384448,2022-06-13 14:41:39+00:00,Ardi_Wdyto,Varian baru omicron lagi :),-7.776581,113.198255,"[varian, baru, omicron, lagi]","[varian, baru, omicron, lagi]","[varian, omicron]"
9337,1536251604772745216,2022-06-13 07:38:19+00:00,gemaposID,BREAKING NEWS!!\nOmicron BA.4 dan BA.5 resmi t...,-6.218042,106.857762,"[breaking, news, omicron, ba, dan, ba, resmi, ...","[breaking, news, omicron, ba, dan, ba, resmi, ...","[breaking, news, omicron, ba, ba, resmi, terde..."

# Stemming Sastrawi (ID)

In [37]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
import swifter

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def stemmed_wrapper(term):
    return stemmer.stem(term)

term_dict={}

for document in df['tweet_stopword']:
    for term in document:
        if term not in term_dict:
            term_dict[term]=' '
            
for term in term_dict:
    term_dict[term]=stemmed_wrapper(term)
    
#apply stemming term ke dataframe
def get_stemmed_term(document):
    return [term_dict[term]for term in document]
    
df['final_tweet'] = df['tweet_stopword'].swifter.apply(get_stemmed_term)
df.head(10)

Pandas Apply:   0%|          | 0/8198 [00:00<?, ?it/s]

,id,date,username,tweet,latitude,longitude,tweet_clean,tweet_normalize,tweet_stopword,final_tweet
0,1387917769501515778,2021-04-29 23:52:37+00:00,MaseebAkhter,3RD JUMMA MUBARAK\nðŸ’– ðŸ’– ðŸ’– ðŸ’– ðŸ’– \n#Ramadan2021 #w...,24.972077,67.064381,"[rd, jumma, mubarak]","[rd, jumma, mubarak]","[rd, jumma, mubarak]","[rd, jumma, mubarak]"
2,1387914934533513220,2021-04-29 23:41:21+00:00,PolsekPlaju3,Bersama Kita Lawan Covid-19\n\nSinergitas TNI-...,-3.190822,104.794609,"[bersama, kita, lawan, covid, sinergitas, tni,...","[bersama, kita, lawan, covid, sinergitas, tni,...","[lawan, covid, sinergitas, tni, polri, mencega...","[lawan, covid, sinergitas, tni, polri, cegah, ..."
3,1387913431865610244,2021-04-29 23:35:22+00:00,irfania_real,Jummah Mubarak \n#irfaniarealestate #jummahmub...,31.315389,74.222395,"[jummah, mubarak]","[jummah, mubarak]","[jummah, mubarak]","[jummah, mubarak]"
4,1387911958393987075,2021-04-29 23:29:31+00:00,kenny_thok,Semangat ya neng!!!!\nIsolasi pake 3M sek....\...,-2.455096,111.930698,"[semangat, ya, neng, isolasi, pake, sek, pondo...","[semangat, ya, neng, isolasi, pakai, sek, pond...","[semangat, ya, neng, isolasi, pakai, sek, pond...","[semangat, ya, neng, isolasi, pakai, sek, pond..."
5,1387907774441566213,2021-04-29 23:12:54+00:00,kejarirohul,"Pada hari Kamis tanggal 29 April 2021, Kepala ...",0.902542,100.308263,"[pada, hari, kamis, tanggal, april, kepala, se...","[pada, hari, kamis, tanggal, april, kepala, se...","[kamis, tanggal, april, kepala, seksi, intelij...","[kamis, tanggal, april, kepala, seksi, intelij..."
6,1387900087645265921,2021-04-29 22:42:21+00:00,eye_healer,System ko changa si se nanga si karnewalo.. ja...,24.373560,92.419839,"[system, ko, changa, si, se, nanga, si, karnew...","[system, ko, changa, si, se, nanga, si, karnew...","[system, ko, changa, si, nanga, si, karnewalo,...","[system, ko, changa, si, nanga, si, karnewalo,..."
7,1387897766102269952,2021-04-29 22:33:07+00:00,sek_batulayar,Jangan Mudik\nBersama Cegah Penyebaran COVID-1...,-8.623126,116.069081,"[jangan, mudik, bersama, cegah, penyebaran, co...","[jangan, mudik, bersama, cegah, penyebaran, co...","[mudik, cegah, penyebaran, covid]","[mudik, cegah, sebar, covid]"
8,1387886247444549633,2021-04-29 21:47:21+00:00,katapang_polsek,Penerapan protokol kesehatan terhadap pengunju...,-7.031984,107.534391,"[penerapan, protokol, kesehatan, terhadap, pen...","[penerapan, protokol, kesehatan, terhadap, pen...","[penerapan, protokol, kesehatan, pengunjung, t...","[terap, protokol, sehat, unjung, tamu, mako, p..."
9,1387885703405572098,2021-04-29 21:45:12+00:00,NabialCG,"Semoga, dan tetap disiplin menjalani prokes\nA...",-7.773728,110.304567,"[semoga, dan, tetap, disiplin, menjalani, prok...","[semoga, dan, tetap, disiplin, menjalani, prok...","[semoga, disiplin, menjalani, prokes, aamiin]","[moga, disiplin, jalan, prokes, aamiin]"
10,1387871604349173765,2021-04-29 20:49:10+00:00,abah_sidik,LPBI NU CIANJUR tergabung bersama TIM ALIF Rel...,-6.739744,107.145685,"[lpbi, nu, cianjur, tergabung, bersama, tim, a...","[lpbi, nu, cianjur, tergabung, bersama, tim, a...","[lpbi, nu, cianjur, tergabung, tim, alif, rela...","[lpbi, nu, cianjur, gabung, tim, alif, rawan, ..."

# Post Stemming

In [38]:
# combine token list to string documents

def remove_punct(text):
    text = ' '.join([char for char in text if char not in string.punctuation])
    return text

df['final_tweet'] = df['final_tweet'].apply(remove_punct)
df

,id,date,username,tweet,latitude,longitude,tweet_clean,tweet_normalize,tweet_stopword,final_tweet
0,1387917769501515778,2021-04-29 23:52:37+00:00,MaseebAkhter,3RD JUMMA MUBARAK\nðŸ’– ðŸ’– ðŸ’– ðŸ’– ðŸ’– \n#Ramadan2021 #w...,24.972077,67.064381,"[rd, jumma, mubarak]","[rd, jumma, mubarak]","[rd, jumma, mubarak]",rd jumma mubarak
2,1387914934533513220,2021-04-29 23:41:21+00:00,PolsekPlaju3,Bersama Kita Lawan Covid-19\n\nSinergitas TNI-...,-3.190822,104.794609,"[bersama, kita, lawan, covid, sinergitas, tni,...","[bersama, kita, lawan, covid, sinergitas, tni,...","[lawan, covid, sinergitas, tni, polri, mencega...",lawan covid sinergitas tni polri cegah tular c...
3,1387913431865610244,2021-04-29 23:35:22+00:00,irfania_real,Jummah Mubarak \n#irfaniarealestate #jummahmub...,31.315389,74.222395,"[jummah, mubarak]","[jummah, mubarak]","[jummah, mubarak]",jummah mubarak
4,1387911958393987075,2021-04-29 23:29:31+00:00,kenny_thok,Semangat ya neng!!!!\nIsolasi pake 3M sek....\...,-2.455096,111.930698,"[semangat, ya, neng, isolasi, pake, sek, pondo...","[semangat, ya, neng, isolasi, pakai, sek, pond...","[semangat, ya, neng, isolasi, pakai, sek, pond...",semangat ya neng isolasi pakai sek pondok deri...
5,1387907774441566213,2021-04-29 23:12:54+00:00,kejarirohul,"Pada hari Kamis tanggal 29 April 2021, Kepala ...",0.902542,100.308263,"[pada, hari, kamis, tanggal, april, kepala, se...","[pada, hari, kamis, tanggal, april, kepala, se...","[kamis, tanggal, april, kepala, seksi, intelij...",kamis tanggal april kepala seksi intelijen ari...
...,...,...,...,...,...,...,...,...,...,...
9332,1536673294782709760,2022-06-14 11:33:58+00:00,StellaSuwardi,Vaksinasi booster dapat meningkatkan imunitas ...,-6.297602,106.770437,"[vaksinasi, booster, dapat, meningkatkan, imun...","[vaksinasi, booster, dapat, meningkatkan, imun...","[vaksinasi, booster, meningkatkan, imunitas, v...",vaksinasi booster tingkat imunitas varian omic...
9333,1536525461077262336,2022-06-14 01:46:31+00:00,natasya_puspa4,Pak Jokowi minta para menterinya mewaspadai da...,-6.364100,106.799599,"[pak, jokowi, minta, para, menterinya, mewaspa...","[pak, jokowi, minta, para, menterinya, mewaspa...","[jokowi, menterinya, mewaspadai, hati, hati, v...",jokowi menteri waspada hati hati varian omicro...
9335,1536515216665899013,2022-06-14 01:05:49+00:00,Agistasyahka,Penyebaran virus Omicron BA.4 dan BA.5 ini leb...,-6.301652,106.974561,"[penyebaran, virus, omicron, ba, dan, ba, ini,...","[penyebaran, virus, omicron, ba, dan, ba, ini,...","[penyebaran, virus, omicron, ba, ba, cepat, di...",sebar virus omicron ba ba cepat banding varian...
9336,1536358141377384448,2022-06-13 14:41:39+00:00,Ardi_Wdyto,Varian baru omicron lagi :),-7.776581,113.198255,"[varian, baru, omicron, lagi]","[varian, baru, omicron, lagi]","[varian, omicron]",varian omicron
9337,1536251604772745216,2022-06-13 07:38:19+00:00,gemaposID,BREAKING NEWS!!\nOmicron BA.4 dan BA.5 resmi t...,-6.218042,106.857762,"[breaking, news, omicron, ba, dan, ba, resmi, ...","[breaking, news, omicron, ba, dan, ba, resmi, ...","[breaking, news, omicron, ba, ba, resmi, terde...",breaking news omicron ba ba resmi deteksi indo...

In [39]:
#remove duplicates

df.drop_duplicates(subset="final_tweet", keep="first", inplace=True)
df

,id,date,username,tweet,latitude,longitude,tweet_clean,tweet_normalize,tweet_stopword,final_tweet
0,1387917769501515778,2021-04-29 23:52:37+00:00,MaseebAkhter,3RD JUMMA MUBARAK\nðŸ’– ðŸ’– ðŸ’– ðŸ’– ðŸ’– \n#Ramadan2021 #w...,24.972077,67.064381,"[rd, jumma, mubarak]","[rd, jumma, mubarak]","[rd, jumma, mubarak]",rd jumma mubarak
2,1387914934533513220,2021-04-29 23:41:21+00:00,PolsekPlaju3,Bersama Kita Lawan Covid-19\n\nSinergitas TNI-...,-3.190822,104.794609,"[bersama, kita, lawan, covid, sinergitas, tni,...","[bersama, kita, lawan, covid, sinergitas, tni,...","[lawan, covid, sinergitas, tni, polri, mencega...",lawan covid sinergitas tni polri cegah tular c...
3,1387913431865610244,2021-04-29 23:35:22+00:00,irfania_real,Jummah Mubarak \n#irfaniarealestate #jummahmub...,31.315389,74.222395,"[jummah, mubarak]","[jummah, mubarak]","[jummah, mubarak]",jummah mubarak
4,1387911958393987075,2021-04-29 23:29:31+00:00,kenny_thok,Semangat ya neng!!!!\nIsolasi pake 3M sek....\...,-2.455096,111.930698,"[semangat, ya, neng, isolasi, pake, sek, pondo...","[semangat, ya, neng, isolasi, pakai, sek, pond...","[semangat, ya, neng, isolasi, pakai, sek, pond...",semangat ya neng isolasi pakai sek pondok deri...
5,1387907774441566213,2021-04-29 23:12:54+00:00,kejarirohul,"Pada hari Kamis tanggal 29 April 2021, Kepala ...",0.902542,100.308263,"[pada, hari, kamis, tanggal, april, kepala, se...","[pada, hari, kamis, tanggal, april, kepala, se...","[kamis, tanggal, april, kepala, seksi, intelij...",kamis tanggal april kepala seksi intelijen ari...
...,...,...,...,...,...,...,...,...,...,...
9332,1536673294782709760,2022-06-14 11:33:58+00:00,StellaSuwardi,Vaksinasi booster dapat meningkatkan imunitas ...,-6.297602,106.770437,"[vaksinasi, booster, dapat, meningkatkan, imun...","[vaksinasi, booster, dapat, meningkatkan, imun...","[vaksinasi, booster, meningkatkan, imunitas, v...",vaksinasi booster tingkat imunitas varian omic...
9333,1536525461077262336,2022-06-14 01:46:31+00:00,natasya_puspa4,Pak Jokowi minta para menterinya mewaspadai da...,-6.364100,106.799599,"[pak, jokowi, minta, para, menterinya, mewaspa...","[pak, jokowi, minta, para, menterinya, mewaspa...","[jokowi, menterinya, mewaspadai, hati, hati, v...",jokowi menteri waspada hati hati varian omicro...
9335,1536515216665899013,2022-06-14 01:05:49+00:00,Agistasyahka,Penyebaran virus Omicron BA.4 dan BA.5 ini leb...,-6.301652,106.974561,"[penyebaran, virus, omicron, ba, dan, ba, ini,...","[penyebaran, virus, omicron, ba, dan, ba, ini,...","[penyebaran, virus, omicron, ba, ba, cepat, di...",sebar virus omicron ba ba cepat banding varian...
9336,1536358141377384448,2022-06-13 14:41:39+00:00,Ardi_Wdyto,Varian baru omicron lagi :),-7.776581,113.198255,"[varian, baru, omicron, lagi]","[varian, baru, omicron, lagi]","[varian, omicron]",varian omicron
9337,1536251604772745216,2022-06-13 07:38:19+00:00,gemaposID,BREAKING NEWS!!\nOmicron BA.4 dan BA.5 resmi t...,-6.218042,106.857762,"[breaking, news, omicron, ba, dan, ba, resmi, ...","[breaking, news, omicron, ba, dan, ba, resmi, ...","[breaking, news, omicron, ba, ba, resmi, terde...",breaking news omicron ba ba resmi deteksi indo...

In [40]:
df.drop(columns=['tweet','tweet_clean','tweet_normalize','tweet_stopword'],axis=1,inplace=True)
df.head(5)

,id,date,username,latitude,longitude,final_tweet
0,1387917769501515778,2021-04-29 23:52:37+00:00,MaseebAkhter,24.972077,67.064381,rd jumma mubarak
2,1387914934533513220,2021-04-29 23:41:21+00:00,PolsekPlaju3,-3.190822,104.794609,lawan covid sinergitas tni polri cegah tular c...
3,1387913431865610244,2021-04-29 23:35:22+00:00,irfania_real,31.315389,74.222395,jummah mubarak
4,1387911958393987075,2021-04-29 23:29:31+00:00,kenny_thok,-2.455096,111.930698,semangat ya neng isolasi pakai sek pondok deri...
5,1387907774441566213,2021-04-29 23:12:54+00:00,kejarirohul,0.902542,100.308263,kamis tanggal april kepala seksi intelijen ari...

In [41]:
df.to_csv('HasilPreProcess.csv')
df

,id,date,username,latitude,longitude,final_tweet
0,1387917769501515778,2021-04-29 23:52:37+00:00,MaseebAkhter,24.972077,67.064381,rd jumma mubarak
2,1387914934533513220,2021-04-29 23:41:21+00:00,PolsekPlaju3,-3.190822,104.794609,lawan covid sinergitas tni polri cegah tular c...
3,1387913431865610244,2021-04-29 23:35:22+00:00,irfania_real,31.315389,74.222395,jummah mubarak
4,1387911958393987075,2021-04-29 23:29:31+00:00,kenny_thok,-2.455096,111.930698,semangat ya neng isolasi pakai sek pondok deri...
5,1387907774441566213,2021-04-29 23:12:54+00:00,kejarirohul,0.902542,100.308263,kamis tanggal april kepala seksi intelijen ari...
...,...,...,...,...,...,...
9332,1536673294782709760,2022-06-14 11:33:58+00:00,StellaSuwardi,-6.297602,106.770437,vaksinasi booster tingkat imunitas varian omic...
9333,1536525461077262336,2022-06-14 01:46:31+00:00,natasya_puspa4,-6.364100,106.799599,jokowi menteri waspada hati hati varian omicro...
9335,1536515216665899013,2022-06-14 01:05:49+00:00,Agistasyahka,-6.301652,106.974561,sebar virus omicron ba ba cepat banding varian...
9336,1536358141377384448,2022-06-13 14:41:39+00:00,Ardi_Wdyto,-7.776581,113.198255,varian omicron
9337,1536251604772745216,2022-06-13 07:38:19+00:00,gemaposID,-6.218042,106.857762,breaking news omicron ba ba resmi deteksi indo...

# TF-IDF Algorithm

In [3]:
df = pd.read_csv('HasilPreProcess.csv')
df

,Unnamed: 0,id,date,username,latitude,longitude,final_tweet
0,0,1387917769501515778,2021-04-29 23:52:37+00:00,MaseebAkhter,24.972077,67.064381,rd jumma mubarak
1,2,1387914934533513220,2021-04-29 23:41:21+00:00,PolsekPlaju3,-3.190822,104.794609,lawan covid sinergitas tni polri cegah tular c...
2,3,1387913431865610244,2021-04-29 23:35:22+00:00,irfania_real,31.315389,74.222395,jummah mubarak
3,4,1387911958393987075,2021-04-29 23:29:31+00:00,kenny_thok,-2.455096,111.930698,semangat ya neng isolasi pakai sek pondok deri...
4,5,1387907774441566213,2021-04-29 23:12:54+00:00,kejarirohul,0.902542,100.308263,kamis tanggal april kepala seksi intelijen ari...
...,...,...,...,...,...,...,...
8109,9332,1536673294782709760,2022-06-14 11:33:58+00:00,StellaSuwardi,-6.297602,106.770437,vaksinasi booster tingkat imunitas varian omic...
8110,9333,1536525461077262336,2022-06-14 01:46:31+00:00,natasya_puspa4,-6.364100,106.799599,jokowi menteri waspada hati hati varian omicro...
8111,9335,1536515216665899013,2022-06-14 01:05:49+00:00,Agistasyahka,-6.301652,106.974561,sebar virus omicron ba ba cepat banding varian...
8112,9336,1536358141377384448,2022-06-13 14:41:39+00:00,Ardi_Wdyto,-7.776581,113.198255,varian omicron
8113,9337,1536251604772745216,2022-06-13 07:38:19+00:00,gemaposID,-6.218042,106.857762,breaking news omicron ba ba resmi deteksi indo...

In [10]:
df.drop(columns=['unnamed: 0']),axis=1,inplace=True)
df.head(5)

SyntaxError: cannot assign to function call (2510599576.py, line 1)

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

final_tweet = df['final_tweet']

# Create TF-IDF matrix
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(final_tweet)

# Print feature names
print(vectorizer.get_feature_names())

# Print TF-IDF matrix
print(tfidf_matrix.toarray())

ValueError: np.nan is an invalid document, expected byte or unicode string.

In [6]:
from nltk.tokenize import word_tokenize

def word_tokenize_wrapper(text):
    return word_tokenize(text)

df['tweet_token'] = df['final_tweet'].apply(word_tokenize_wrapper)

df.head(5)

TypeError: expected string or bytes-like object

In [51]:
# convert list formated string to list
import ast

def convert_text_list(texts):
    texts = ast.literal_eval(texts)
    return [text for text in texts]

df["tweet_list"] = df["tweet_token"].apply(convert_text_list)


print(df["tweet_list"][90])

print("\ntype : ", type(df["tweet_list"][90]))

ValueError: malformed node or string: ['rd', 'jumma', 'mubarak']

In [52]:
def calc_TF(document):
    # Counts the number of times the word appears in review
    TF_dict = {}
    for term in document:
        if term in TF_dict:
            TF_dict[term] += 1
        else:
            TF_dict[term] = 1
    # Computes tf for each word
    for term in TF_dict:
        TF_dict[term] = TF_dict[term] / len(document)
    return TF_dict

df["TF_dict"] = df['tweet_list'].apply(calc_TF)

df["TF_dict"].head()

KeyError: 'tweet_list'